
[default]
SECRET_KEY="@jinja {{env.SECRET_KEY}}"
SEND_GRID_CLIENT_KEY="@jinja {{env.SEND_GRID_CLIENT_KEY}}"
EMAIL_SEND_GRID="@jinja {{env.EMAIL_SEND_GRID}}"

[development]
MONGODB_SETTINGS={host="@jinja {{env.DATABASE_DEV}}"}

[production]
MONGODB_SETTINGS={host="@jinja {{env.DATABASE_PRODUCTION}}"}

[testing]
MONGODB_SETTINGS={host="@jinja {{env.DATABASE_TESTING}}"}